name: publish-coder-feature

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish Feature to GHCR
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./"
