name: Run Command in Codespace

on:
  workflow_dispatch:
    inputs:
      codespace:
        description: "The Codespace name or ID to operate on."
        required: true
      command:
        description: "The terminal command to execute inside the Codespace."
        required: true

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI if needed
        run: |
          if ! command -v gh >/dev/null; then
            sudo apt-get update && sudo apt-get install -y gh
          fi

      # Create private key file from your GitHub secret
      - name: Prepare pat
        run: |
          export GH_PAT="${{ secrets.GH_PAT }}"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GH_PAT }}" | gh auth login -p https --with-token > /dev/null

      - name: echo Codespace details
        run: gh codespace list

      - name: Unpause Codespace
        run: gh codespace rebuild -c "${{ github.event.inputs.codespace }}" > /dev/null

      - name: Run repo setup
        run: gh codespace ssh -c "${{ github.event.inputs.codespace }}" -- "export GH_PAT=${{ secrets.GH_PAT }} && ./sync/clone.sh" > /dev/null

      - name: Execute Terminal Command
        run: gh codespace ssh -c "${{ github.event.inputs.codespace }}" -- ${{ github.event.inputs.command }} > /dev/null
